site_name: Headroom
copyright: Copyright (c) 2020 norcane

theme:
  name: material
  logo: "images/norcane-logo.png"

  features:
    - tabs

  custom_dir: overrides

markdown_extensions:
  - codehilite:
      guess_lang: false
      use_pygments: true

nav:
  - Home: index.md
  - Documentation:
      - Installation: documentation/installation.md
      - Basic Concepts: documentation/basic-concepts.md
      - Project Setup Guide: documentation/project-setup-guide.md
      - Running Headroom: documentation/running-headroom.md
      - Configuration: documentation/configuration.md
